openapi: 3.0.0
info:
  title: CollabAI Backend API
  description: API documentation for the CollabAI application
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://api.collabai.denzeliskandar.com
    description: Production server

paths:
  /:
    get:
      summary: Health check
      description: Check if the server is running
      responses:
        '200':
          description: Server is up
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Server is up!"

  /auth/register:
    post:
      summary: Register a new user
      description: Create a new user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
                - username
              properties:
                name:
                  type: string
                  example: "John Doe"
                email:
                  type: string
                  format: email
                  example: "john@example.com"
                password:
                  type: string
                  format: password
                  example: "securepassword"
                username:
                  type: string
                  example: "johndoe"
                profilePic:
                  type: string
                  description: Base64 encoded image (optional)
      responses:
        '200':
          description: User successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
                  profilePic:
                    type: string

  /auth/login:
    post:
      summary: Login a user
      description: Authenticate user credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: "john@example.com"
                password:
                  type: string
                  format: password
                  example: "securepassword"
      responses:
        '200':
          description: User successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
                  profilePic:
                    type: string

  /auth/logout:
    post:
      summary: Logout a user
      description: End user session
      security:
        - cookieAuth: []
      responses:
        '200':
          description: User successfully logged out

  /user/profile:
    get:
      summary: Get user profile
      description: Retrieve the current user's profile information
      security:
        - cookieAuth: []
      responses:
        '200':
          description: User profile information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /project:
    post:
      summary: Create a new project
      description: Create a new project
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: "My Project"
      responses:
        '200':
          description: Project successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'

  /project/list:
    get:
      summary: List all projects for a user
      description: Get all projects that the user is a member of
      security:
        - cookieAuth: []
      responses:
        '200':
          description: List of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'

  /project/{id}:
    get:
      summary: Get details of a project
      description: Retrieve detailed information about a specific project
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
    delete:
      summary: Delete a project
      description: Remove a project from the system
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project successfully deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
                
  /project/{id}/graph:
    get:
      summary: Get graph view of a project
      description: Retrieve common topics and their edges
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project graph data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object

  /project/join:
    post:
      summary: Join a project
      description: Join an existing project using its code
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - code
              properties:
                code:
                  type: string
                  example: "ABC123"
      responses:
        '200':
          description: Successfully joined project
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'

  /project/{id}/send:
    post:
      summary: Send a message to a project
      description: Add a new message to the project chat
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  example: "Hello team!"
      responses:
        '200':
          description: Message successfully sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    description: Message object returned

  /project/data/{id}:
    get:
      summary: Get file data from a project
      description: Retrieve a data source URL from a project
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: URL to access the file data
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: URL to access the file
    delete:
      summary: Delete a file from a project
      description: Remove a data source from a project
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File successfully deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSource'

  /project/{id}/upload:
    post:
      summary: Upload a file to a project
      description: Upload a data source file to a project
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File successfully uploaded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSource'

  /project/{id}/collaborator:
    post:
      summary: Add a collaborator to a project
      description: Add a user as a collaborator to a project using their email
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  example: "collaborator@example.com"
      responses:
        '200':
          description: Collaborator successfully added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: accessToken
      description: Authentication using HTTP cookies (accessToken and refreshToken)

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        username:
          type: string
        profilePic:
          type: string

    Project:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        code:
          type: string
        isArchived:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
        dataSources:
          type: array
          items:
            $ref: '#/components/schemas/DataSource'

    Message:
      type: object
      properties:
        id:
          type: string
        content:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        user:
          $ref: '#/components/schemas/User'

    DataSource:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        size:
          type: number
        type:
          type: string
        url:
          type: string
        createdAt:
          type: string
          format: date-time
